title: Sheilla Mae Rico
email: sheillamae.srico@gmail.com
description: >-
  Software Engineer passionate about Java, fullstack development, databases,
  and cloud technologies. Showcasing projects, skills, and continuous learning.

baseurl: ""
url: "https://sheillarico.github.io"

github_username: sheillarico
linkedin_username: sheillarico

author:
  name: Sheilla Mae Rico