title: Sheilla Mae Rico
email: sheillamae.srico@gmail.com
description: >-
  Computer Science Graduate | Software Development | Java | Cloud Engineering | Portfolio

baseurl: ""
url: "https://sheillarico.github.io"

github_username: sheillarico
linkedin_username: sheillarico

author:
  name: Sheilla Mae Rico